### ISSUE TITLE
Container needs GDAL

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/tuple#23]
The WPS container will need to have GDAL installed: its libs are used to build PDAL and friends, and its command-line tools are invoked by the WPS groovy script.

**Comment by benhosmer** [comment]
Is there a specific version? Can we go with 1.7.3 available in EPEL?

On Thu, Mar 26, 2015 at 3:37 PM, Michael P. Gerlek <notifications@github.com
> wrote:

> The WPS container will need to have GDAL installed: its libs are used to
> build PDAL and friends, and its command-line tools are invoked by the WPS
> groovy script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/tuple/issues/23>.
>



-- 
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by mpgerlek** [comment]
Yes, the latest 1.x release should work. Don’t go to 2.x though...

-mpg



On Mar 26, 2015, at 3:40 PM, Ben Hosmer <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there a specific version? Can we go with 1.7.3 available in EPEL?

On Thu, Mar 26, 2015 at 3:37 PM, Michael P. Gerlek <notifications@github.com<mailto:notifications@github.com>
> wrote:

> The WPS container will need to have GDAL installed: its libs are used to
> build PDAL and friends, and its command-line tools are invoked by the WPS
> groovy script.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radiantbluetechnologies/tuple/issues/23>.
>



--
Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by benhosmer** [comment]
closed with https://github.com/benhosmer/tuple/commit/47f466947f47f63e306ce14de7f078422891c754
