### ISSUE TITLE
Tomcat needs CORS turned off

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/tuple#24]
We need to disable CORS on tomcat.

When the viewer makes a WPS request directly from Javascript, I get CORS errors. But when I tunnel through my own private proxy, it works fine.

**Comment by benhosmer** [comment]
A hint for where to set this:

`geoserver/WEB-INF/web.xml`

```
<filter>
  <filter-name>CorsFilter</filter-name>
  <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
</filter>
<filter-mapping>
  <filter-name>CorsFilter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
```

**Comment by mpgerlek** [comment]
(verified)
