### ISSUE TITLE
WPS hello-world script

### ISSUE THREAD

**Issue by mpgerlek** [radiantbluetechnologies/tuple#26]
We need to have a hello-world / ping groovy WPS script installed, to verify everything's working without having to run ossim itself.

mpg will set up the script and then kick it over to @benhosmer

**Comment by mpgerlek** [comment]
@benhosmer Pls add "docker/tuple-wps/wpshelloworld.groovy" to the tuple-wps container

**Comment by benhosmer** [comment]
Currently what I've done is add the scripts when the container is launched. I've added instructions on how to do this in the [README](https://github.com/benhosmer/tuple/blob/develop/docker/tuple-wps/README.md) with a shared volume. This way you can dynamically add scripts without rebuilding the container each time. This was incorporated in my batch of recent pull requests.
